# -*- coding: utf-8 -*-
"""HW_1p1_Task3_fremontm.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SKs4Ai_Vy-bI2Ep2WVa8o0ixnfl2FLGY
"""

# HW 1 Task 3
# File: HW_1p1_Task3_fremontm.py 
# Date:    20 01 2022
# By:      Tyler Fremon
# Section: 001
# Team:    004
# 
# ELECTRONIC SIGNATURE
# Tyler Fremon
#
# The electronic signature above indicates the script
# submitted for evaluation is my individual work, and I
# have a general understanding of all aspects of its
# development and execution.
#
# A BRIEF DESCRIPTION OF WHAT THE SCRIPT OR FUNCTION DOES
# Determines min or max of inputted list through conditional/looped structure
# Note: I do my coding in Google Colaboratory as opposed to IDLE, hence included message.

55
5# Intialise and append entries
r = int((input('Input number of list elements ')))
list = []
for x in range(r):
  element = float(input('Input list element {0} (index {1}): ' .format(x+1, x)))
  list.append(element)

# Set max and min to first element
max = list[0]
min = list[0]
for element in list:
  # Can skip first element as already set to min/max and will be left untouched if min or max
  if element >= max:
    max = element
  if element <= min:
    min = element
print('N = {0} , Minimum = {1}, Maximum = {2} ' .format(r, min, max))
